import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className='bg-gradient-to-r from-primary to-secondary'>

    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Chronicles - Personal Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
    <Header />

    <div className="flex justify-between items-center border-y border-fontColor py-10 lg:py-0">
      <div className="px-10 space-y-5">
        <h1 className="text-6xl max-w-xl font-serif">
          <span className="underline decoration-black decoration-4">Chronicles</span>{" "} is a place to write, read, and connect
        </h1>
        <h2>It's easy and free to post your thinking on any topic and connect with millions of readers.</h2>
      </div>
    
      <img className="hidden md:inline-flex h-32 lg:px-4 lg:py-8 lg:h-full" src="/images/icon.svg" alt="icon"/>  
      </div>
      {/* Post */}
    </div>
  


  </div>
  )
}

export default Home
