import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header'
import { sanityClient, urlFor} from '../sanity'
import { Post } from '../typing'

interface Props {
  posts: [Post];
}

export default function Home({ posts }: Props) {
  return (
    <div>
        <div className='bg-cover bg-center bg-fixed bg-[url(https://i.imgur.com/6JieORA.jpg)]'>
         
            <Head>
              <title>Chronicles - Personal Blog Site</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

        <div className="border-b border-white">
          <Header />
        </div>
        
        <div className="max-w-7xl mx-auto">
          <div className="flex justify-between items-center py-10 lg:py-0">
            <div className="px-10 space-y-8">
              <h1 className="text-7xl text-white max-w-xl font-thin font-serif">My Chronicles.</h1>
              <h2 className="text-xl text-white max-w-xl">Personal journal. Chronicle is a collection of all of my projects that I document from design, development and production. And interesting articles aswell.</h2>
              <Link href="/"><a className="block text-fontColor bg-white hover:text-white hover:bg-slate-800 px-6 py-3 font-medium rounded-full transition-all max-w-xl w-fit">Read Latest Article</a></Link>
            </div>
            <img className="hidden md:inline-flex h-32 lg:px-4 lg:py-8 lg:h-full" src="https://i.imgur.com/Y3VF6fA.png" alt="icon"/>  
            </div>
          </div>
        </div>

          {/* Post */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6">
        {posts.map(post => (
          <Link key={post._id} href={`/post/${post.slug.current}`}>
            <div className="border rounded-lg group cursor-pointer overflow-hidden">
              <img className="h-60 w-full object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out" src={urlFor(post.mainImage).url()!} alt=""/>
            <div className="flex justify-between p-5 bg-white">
              <div>
              <p className="text-lg font-bold">{post.title}</p>
              <p className="text-sm">{post.description} by {post.author.name}</p>
            </div>

            <img className="h-12 w-12 rounded-full" src={urlFor(post.author.image).url()!} alt="" />
              </div>
            </div>
          </Link>
        ))}
        </div>
  </div>
  )
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author -> {
    name,
    image
  },
  description,
  mainImage,
  slug
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    }
  }
}
